// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CsvToJMat
void CsvToJMat(std::string ifname, std::string ofname, std::string mtype, char csep, std::string ctype, std::string valuetype, bool transpose, std::string comment);
RcppExport SEXP _parallelpam_CsvToJMat(SEXP ifnameSEXP, SEXP ofnameSEXP, SEXP mtypeSEXP, SEXP csepSEXP, SEXP ctypeSEXP, SEXP valuetypeSEXP, SEXP transposeSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ifname(ifnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type ofname(ofnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type mtype(mtypeSEXP);
    Rcpp::traits::input_parameter< char >::type csep(csepSEXP);
    Rcpp::traits::input_parameter< std::string >::type ctype(ctypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type valuetype(valuetypeSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    Rcpp::traits::input_parameter< std::string >::type comment(commentSEXP);
    CsvToJMat(ifname, ofname, mtype, csep, ctype, valuetype, transpose, comment);
    return R_NilValue;
END_RCPP
}
// JMatToCsv
void JMatToCsv(std::string ifile, std::string csvfile, char csep, bool withquotes);
RcppExport SEXP _parallelpam_JMatToCsv(SEXP ifileSEXP, SEXP csvfileSEXP, SEXP csepSEXP, SEXP withquotesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ifile(ifileSEXP);
    Rcpp::traits::input_parameter< std::string >::type csvfile(csvfileSEXP);
    Rcpp::traits::input_parameter< char >::type csep(csepSEXP);
    Rcpp::traits::input_parameter< bool >::type withquotes(withquotesSEXP);
    JMatToCsv(ifile, csvfile, csep, withquotes);
    return R_NilValue;
END_RCPP
}
// ParallelpamSetDebug
void ParallelpamSetDebug(bool deb, bool debjmat);
RcppExport SEXP _parallelpam_ParallelpamSetDebug(SEXP debSEXP, SEXP debjmatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type deb(debSEXP);
    Rcpp::traits::input_parameter< bool >::type debjmat(debjmatSEXP);
    ParallelpamSetDebug(deb, debjmat);
    return R_NilValue;
END_RCPP
}
// CalcAndWriteDissimilarityMatrix
void CalcAndWriteDissimilarityMatrix(std::string ifname, std::string ofname, std::string distype, std::string restype, std::string comment, int nthreads);
RcppExport SEXP _parallelpam_CalcAndWriteDissimilarityMatrix(SEXP ifnameSEXP, SEXP ofnameSEXP, SEXP distypeSEXP, SEXP restypeSEXP, SEXP commentSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ifname(ifnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type ofname(ofnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type distype(distypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type restype(restypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type comment(commentSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    CalcAndWriteDissimilarityMatrix(ifname, ofname, distype, restype, comment, nthreads);
    return R_NilValue;
END_RCPP
}
// FilterJMatByName
void FilterJMatByName(std::string fname, Rcpp::StringVector Gn, std::string filname, std::string namesat);
RcppExport SEXP _parallelpam_FilterJMatByName(SEXP fnameSEXP, SEXP GnSEXP, SEXP filnameSEXP, SEXP namesatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type Gn(GnSEXP);
    Rcpp::traits::input_parameter< std::string >::type filname(filnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type namesat(namesatSEXP);
    FilterJMatByName(fname, Gn, filname, namesat);
    return R_NilValue;
END_RCPP
}
// FilterBySilhouetteQuantile
Rcpp::List FilterBySilhouetteQuantile(Rcpp::NumericVector s, Rcpp::List L, std::string fallcounts, std::string ffilcounts, std::string falldissim, std::string ffildissim, float q, bool addcom);
RcppExport SEXP _parallelpam_FilterBySilhouetteQuantile(SEXP sSEXP, SEXP LSEXP, SEXP fallcountsSEXP, SEXP ffilcountsSEXP, SEXP falldissimSEXP, SEXP ffildissimSEXP, SEXP qSEXP, SEXP addcomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    Rcpp::traits::input_parameter< std::string >::type fallcounts(fallcountsSEXP);
    Rcpp::traits::input_parameter< std::string >::type ffilcounts(ffilcountsSEXP);
    Rcpp::traits::input_parameter< std::string >::type falldissim(falldissimSEXP);
    Rcpp::traits::input_parameter< std::string >::type ffildissim(ffildissimSEXP);
    Rcpp::traits::input_parameter< float >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type addcom(addcomSEXP);
    rcpp_result_gen = Rcpp::wrap(FilterBySilhouetteQuantile(s, L, fallcounts, ffilcounts, falldissim, ffildissim, q, addcom));
    return rcpp_result_gen;
END_RCPP
}
// FilterBySilhouetteThreshold
Rcpp::List FilterBySilhouetteThreshold(Rcpp::NumericVector s, Rcpp::List L, std::string fallcounts, std::string ffilcounts, std::string falldissim, std::string ffildissim, float thres, bool addcom);
RcppExport SEXP _parallelpam_FilterBySilhouetteThreshold(SEXP sSEXP, SEXP LSEXP, SEXP fallcountsSEXP, SEXP ffilcountsSEXP, SEXP falldissimSEXP, SEXP ffildissimSEXP, SEXP thresSEXP, SEXP addcomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    Rcpp::traits::input_parameter< std::string >::type fallcounts(fallcountsSEXP);
    Rcpp::traits::input_parameter< std::string >::type ffilcounts(ffilcountsSEXP);
    Rcpp::traits::input_parameter< std::string >::type falldissim(falldissimSEXP);
    Rcpp::traits::input_parameter< std::string >::type ffildissim(ffildissimSEXP);
    Rcpp::traits::input_parameter< float >::type thres(thresSEXP);
    Rcpp::traits::input_parameter< bool >::type addcom(addcomSEXP);
    rcpp_result_gen = Rcpp::wrap(FilterBySilhouetteThreshold(s, L, fallcounts, ffilcounts, falldissim, ffildissim, thres, addcom));
    return rcpp_result_gen;
END_RCPP
}
// ClassifAsDataFrame
Rcpp::DataFrame ClassifAsDataFrame(Rcpp::List L, std::string fdist);
RcppExport SEXP _parallelpam_ClassifAsDataFrame(SEXP LSEXP, SEXP fdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    Rcpp::traits::input_parameter< std::string >::type fdist(fdistSEXP);
    rcpp_result_gen = Rcpp::wrap(ClassifAsDataFrame(L, fdist));
    return rcpp_result_gen;
END_RCPP
}
// ApplyPAM
Rcpp::List ApplyPAM(std::string dissim_file, int k, std::string init_method, Rcpp::Nullable<Rcpp::NumericVector> initial_med, int max_iter, int nthreads);
RcppExport SEXP _parallelpam_ApplyPAM(SEXP dissim_fileSEXP, SEXP kSEXP, SEXP init_methodSEXP, SEXP initial_medSEXP, SEXP max_iterSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dissim_file(dissim_fileSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_method(init_methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type initial_med(initial_medSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ApplyPAM(dissim_file, k, init_method, initial_med, max_iter, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// GetTD
double GetTD(Rcpp::List L, std::string dissim_file);
RcppExport SEXP _parallelpam_GetTD(SEXP LSEXP, SEXP dissim_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    Rcpp::traits::input_parameter< std::string >::type dissim_file(dissim_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(GetTD(L, dissim_file));
    return rcpp_result_gen;
END_RCPP
}
// GetJCol
Rcpp::NumericVector GetJCol(std::string fname, int ncol);
RcppExport SEXP _parallelpam_GetJCol(SEXP fnameSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJCol(fname, ncol));
    return rcpp_result_gen;
END_RCPP
}
// GetJManyCols
Rcpp::NumericMatrix GetJManyCols(std::string fname, Rcpp::NumericVector extcols);
RcppExport SEXP _parallelpam_GetJManyCols(SEXP fnameSEXP, SEXP extcolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type extcols(extcolsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJManyCols(fname, extcols));
    return rcpp_result_gen;
END_RCPP
}
// GetJColByName
Rcpp::NumericVector GetJColByName(std::string fname, std::string colname);
RcppExport SEXP _parallelpam_GetJColByName(SEXP fnameSEXP, SEXP colnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJColByName(fname, colname));
    return rcpp_result_gen;
END_RCPP
}
// GetJManyColsByNames
Rcpp::NumericMatrix GetJManyColsByNames(std::string fname, Rcpp::StringVector extcolnames);
RcppExport SEXP _parallelpam_GetJManyColsByNames(SEXP fnameSEXP, SEXP extcolnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type extcolnames(extcolnamesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJManyColsByNames(fname, extcolnames));
    return rcpp_result_gen;
END_RCPP
}
// GetSubdiag
Rcpp::NumericVector GetSubdiag(std::string fname);
RcppExport SEXP _parallelpam_GetSubdiag(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSubdiag(fname));
    return rcpp_result_gen;
END_RCPP
}
// GetJRow
Rcpp::NumericVector GetJRow(std::string fname, int nrow);
RcppExport SEXP _parallelpam_GetJRow(SEXP fnameSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJRow(fname, nrow));
    return rcpp_result_gen;
END_RCPP
}
// GetJManyRows
Rcpp::NumericMatrix GetJManyRows(std::string fname, Rcpp::NumericVector extrows);
RcppExport SEXP _parallelpam_GetJManyRows(SEXP fnameSEXP, SEXP extrowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type extrows(extrowsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJManyRows(fname, extrows));
    return rcpp_result_gen;
END_RCPP
}
// GetJRowByName
Rcpp::NumericVector GetJRowByName(std::string fname, std::string rowname);
RcppExport SEXP _parallelpam_GetJRowByName(SEXP fnameSEXP, SEXP rownameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type rowname(rownameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJRowByName(fname, rowname));
    return rcpp_result_gen;
END_RCPP
}
// GetJManyRowsByNames
Rcpp::NumericMatrix GetJManyRowsByNames(std::string fname, Rcpp::StringVector extrownames);
RcppExport SEXP _parallelpam_GetJManyRowsByNames(SEXP fnameSEXP, SEXP extrownamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type extrownames(extrownamesSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJManyRowsByNames(fname, extrownames));
    return rcpp_result_gen;
END_RCPP
}
// JMatInfo
void JMatInfo(std::string fname, std::string fres);
RcppExport SEXP _parallelpam_JMatInfo(SEXP fnameSEXP, SEXP fresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type fres(fresSEXP);
    JMatInfo(fname, fres);
    return R_NilValue;
END_RCPP
}
// GetJRowNames
Rcpp::StringVector GetJRowNames(std::string fname);
RcppExport SEXP _parallelpam_GetJRowNames(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJRowNames(fname));
    return rcpp_result_gen;
END_RCPP
}
// GetJColNames
Rcpp::StringVector GetJColNames(std::string fname);
RcppExport SEXP _parallelpam_GetJColNames(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJColNames(fname));
    return rcpp_result_gen;
END_RCPP
}
// GetJNames
Rcpp::List GetJNames(std::string fname);
RcppExport SEXP _parallelpam_GetJNames(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetJNames(fname));
    return rcpp_result_gen;
END_RCPP
}
// JWriteBin
void JWriteBin(Rcpp::NumericMatrix M, std::string fname, std::string dtype, std::string dmtype, std::string comment);
RcppExport SEXP _parallelpam_JWriteBin(SEXP MSEXP, SEXP fnameSEXP, SEXP dtypeSEXP, SEXP dmtypeSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type dmtype(dmtypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type comment(commentSEXP);
    JWriteBin(M, fname, dtype, dmtype, comment);
    return R_NilValue;
END_RCPP
}
// CalculateSilhouette
Rcpp::NumericVector CalculateSilhouette(Rcpp::NumericVector cl, std::string fdist, int nthreads);
RcppExport SEXP _parallelpam_CalculateSilhouette(SEXP clSEXP, SEXP fdistSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cl(clSEXP);
    Rcpp::traits::input_parameter< std::string >::type fdist(fdistSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(CalculateSilhouette(cl, fdist, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// NumSilToClusterSil
Rcpp::NumericMatrix NumSilToClusterSil(Rcpp::NumericVector cl, Rcpp::NumericVector s);
RcppExport SEXP _parallelpam_NumSilToClusterSil(SEXP clSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type cl(clSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(NumSilToClusterSil(cl, s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parallelpam_CsvToJMat", (DL_FUNC) &_parallelpam_CsvToJMat, 8},
    {"_parallelpam_JMatToCsv", (DL_FUNC) &_parallelpam_JMatToCsv, 4},
    {"_parallelpam_ParallelpamSetDebug", (DL_FUNC) &_parallelpam_ParallelpamSetDebug, 2},
    {"_parallelpam_CalcAndWriteDissimilarityMatrix", (DL_FUNC) &_parallelpam_CalcAndWriteDissimilarityMatrix, 6},
    {"_parallelpam_FilterJMatByName", (DL_FUNC) &_parallelpam_FilterJMatByName, 4},
    {"_parallelpam_FilterBySilhouetteQuantile", (DL_FUNC) &_parallelpam_FilterBySilhouetteQuantile, 8},
    {"_parallelpam_FilterBySilhouetteThreshold", (DL_FUNC) &_parallelpam_FilterBySilhouetteThreshold, 8},
    {"_parallelpam_ClassifAsDataFrame", (DL_FUNC) &_parallelpam_ClassifAsDataFrame, 2},
    {"_parallelpam_ApplyPAM", (DL_FUNC) &_parallelpam_ApplyPAM, 6},
    {"_parallelpam_GetTD", (DL_FUNC) &_parallelpam_GetTD, 2},
    {"_parallelpam_GetJCol", (DL_FUNC) &_parallelpam_GetJCol, 2},
    {"_parallelpam_GetJManyCols", (DL_FUNC) &_parallelpam_GetJManyCols, 2},
    {"_parallelpam_GetJColByName", (DL_FUNC) &_parallelpam_GetJColByName, 2},
    {"_parallelpam_GetJManyColsByNames", (DL_FUNC) &_parallelpam_GetJManyColsByNames, 2},
    {"_parallelpam_GetSubdiag", (DL_FUNC) &_parallelpam_GetSubdiag, 1},
    {"_parallelpam_GetJRow", (DL_FUNC) &_parallelpam_GetJRow, 2},
    {"_parallelpam_GetJManyRows", (DL_FUNC) &_parallelpam_GetJManyRows, 2},
    {"_parallelpam_GetJRowByName", (DL_FUNC) &_parallelpam_GetJRowByName, 2},
    {"_parallelpam_GetJManyRowsByNames", (DL_FUNC) &_parallelpam_GetJManyRowsByNames, 2},
    {"_parallelpam_JMatInfo", (DL_FUNC) &_parallelpam_JMatInfo, 2},
    {"_parallelpam_GetJRowNames", (DL_FUNC) &_parallelpam_GetJRowNames, 1},
    {"_parallelpam_GetJColNames", (DL_FUNC) &_parallelpam_GetJColNames, 1},
    {"_parallelpam_GetJNames", (DL_FUNC) &_parallelpam_GetJNames, 1},
    {"_parallelpam_JWriteBin", (DL_FUNC) &_parallelpam_JWriteBin, 5},
    {"_parallelpam_CalculateSilhouette", (DL_FUNC) &_parallelpam_CalculateSilhouette, 3},
    {"_parallelpam_NumSilToClusterSil", (DL_FUNC) &_parallelpam_NumSilToClusterSil, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_parallelpam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
